CREATE TABLE jb_volume (
Id BIGINT NOT NULL AUTO_INCREMENT, 
agencyVolume BOOL NOT NULL, 
bookDescription VARCHAR(255) NULL, 
bookGroup VARCHAR(255) NOT NULL, 
bookLabel VARCHAR(255) NULL, 
bookNumber VARCHAR(255) NULL, 
generateLineItemTocByBA BOOL NOT NULL, 
generateLineItemTocByTitle BOOL NOT NULL, 
generateP1 BOOL NOT NULL, 
generateProgramElementTocByBA BOOL NOT NULL, 
generateProgramElementTocByTitle BOOL NOT NULL, 
generateR1 BOOL NOT NULL, 
generateR1Summary BOOL NOT NULL, 
generateR1c BOOL NOT NULL, 
generateR1d BOOL NOT NULL, 
overrideDocumentAssemblyOptionsInXml BOOL NOT NULL, 
p40Volume BOOL NOT NULL, 
serviceAgencyId BIGINT NULL, 
PRIMARY KEY (Id), 
KEY (serviceAgencyId)) ENGINE=InnoDB DEFAULT CHARSET=utf8;