ALTER TABLE `PROJECT_SCHEDULE_PROFILE` 
CHANGE COLUMN `PSP_IMAGE_NAME` `PSP_IMAGE_NAME` VARCHAR(255) NOT NULL COMMENT '' ,
CHANGE COLUMN `PSP_IMAGE_DATA` `PSP_IMAGE_DATA` MEDIUMBLOB NOT NULL COMMENT '' ,
CHANGE COLUMN `PSP_THUMBNAIL_IMAGE_DATA` `PSP_THUMBNAIL_IMAGE_DATA` MEDIUMBLOB NOT NULL COMMENT '' ;