SET TIME_ZONE='+00:00';
SET UNIQUE_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET SQL_NOTES=0;


DROP VIEW IF EXISTS v_pe_suffix;

CREATE ALGORITHM=UNDEFINED
VIEW `v_pe_suffix` AS
SELECT `PS_SUFFIX`, `PS_SERV_AGY_ID` 
FROM `PE_SUFFIX` 
WHERE `PS_DATE_INACTIVE` IS NULL;

