package gov.va.vba.vbms.common.framework.performance.impl;

public interface FieldSizes {
	int USERNAME_FIELD_SIZE = 64;
	int CLASSNAME_FIELD_SIZE = 128;
	int METHODNAME_FIELD_SIZE = 128;
	int HOST_FIELD_SIZE = 64;
	int EXCEPTIONMESSAGE_FIELD_SIZE = 4000;
	int EXCEPTIONTYPE_FIELD_SIZE = 256;
	int PATH_FIELD_SIZE = 128;
	int PROFILE_FIELD_SIZE = 2000;
	int USERROLE_FIELD_SIZE = 2000;
    int METHODSOURCE_FIELD_SIZE = 64;
    int SERVERNAME_FIELD_SIZE = 64;
}