insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Coast Guard Support' AND a.BUDGES_APPROP_ACCT_CODE = '0380N' AND a.BUDGES_APPROP_ACCT_NAME = 'Coastal Defense Augmentation' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '1' ,'Coast Guard Support', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 2 AND ba.ba_title = 'Communications & Electronics Equip' AND a.BUDGES_APPROP_ACCT_CODE = '1810N' AND a.BUDGES_APPROP_ACCT_NAME = 'Other Procurement, Navy' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '96' ,'Elect Equip - Mods Tactical Sys/Eq', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Major Equipment' AND a.BUDGES_APPROP_ACCT_CODE = '0300D' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement, Defense-Wide' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '10' ,'Equipment', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '1109N' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement, Marine Corps' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '16' ,'Flares', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 2 AND ba.ba_title = 'National Guard Equipment' AND a.BUDGES_APPROP_ACCT_CODE = '0350D' AND a.BUDGES_APPROP_ACCT_NAME = 'National Guard and Reserve Equipment' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '30' ,'National Guard Aircraft', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 29 AND ba.ba_title = 'Offset/Asset' AND a.BUDGES_APPROP_ACCT_CODE = '1810N' AND a.BUDGES_APPROP_ACCT_NAME = 'Other Procurement, Navy' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '99' ,'Offsets/Assets', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 29 AND ba.ba_title = 'Offset/Asset' AND a.BUDGES_APPROP_ACCT_CODE = '2035A' AND a.BUDGES_APPROP_ACCT_NAME = 'Other Procurement, Army' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '99' ,'Offsets/Assets', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Operation & Maintenance' AND a.BUDGES_APPROP_ACCT_CODE = '0130' AND a.BUDGES_APPROP_ACCT_NAME = 'Defense Health Program' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '1' ,'Operation & Maintenance', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 3 AND ba.ba_title = 'Procurement' AND a.BUDGES_APPROP_ACCT_CODE = '0390A' AND a.BUDGES_APPROP_ACCT_NAME = 'Chem Agents & Munitions Ds, Army' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '1' ,'Procurement', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 4 AND ba.ba_title = 'Military Construction' AND a.BUDGES_APPROP_ACCT_CODE = '0390A' AND a.BUDGES_APPROP_ACCT_NAME = 'Chem Agents & Munitions Ds, Army' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '1' ,'Retrograde', 'A');
