ALTER TABLE `PROJECT_JOINT_FUNDING`
ADD COLUMN `JF_BY2` decimal(12,3) unsigned DEFAULT NULL AFTER JF_BY1_OCO,
ADD COLUMN `JF_BY3` decimal(12,3) unsigned DEFAULT NULL AFTER JF_BY2,
ADD COLUMN `JF_BY4` decimal(12,3) unsigned DEFAULT NULL AFTER JF_BY3,
ADD COLUMN `JF_BY5` decimal(12,3) unsigned DEFAULT NULL AFTER JF_BY4,
ADD COLUMN `JF_BY6` decimal(12,3) unsigned DEFAULT NULL AFTER JF_BY5;
