SET @DHP_USERS = (SELECT BUDGES_USER_ID FROM USER_SERVICE_AGENCY WHERE BUDGES_SERV_AGY_ID = 
				  (SELECT BUDGES_SERV_AGY_ID FROM SERVICE_AGENCY WHERE BUDGES_SERV_AGY_CODE = 'DHP'));

INSERT into USER_SERVICE_AGENCY (BUDGES_USER_ID, BUDGES_SERV_AGY_ID) values 
(@DHP_USERS, (SELECT BUDGES_SERV_AGY_ID FROM SERVICE_AGENCY WHERE BUDGES_SERV_AGY_CODE = 'DHA'));