SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `hp_to_cmtf` (
  `HP_TO_CMTF_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `hp_ID` int(10) unsigned NOT NULL,
  `cmtf_ID` smallint(5) unsigned NOT NULL,
  `CREATED_BY_USER` varchar(256) DEFAULT NULL,
  `DATE_CREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MODIFIED_BY_USER` varchar(256) DEFAULT NULL,
  `DATE_MODIFIED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`HP_TO_CMTF_ID`),
  UNIQUE KEY `UN_HP_TO_CMTF_ID` (`HP_TO_CMTF_ID`) USING BTREE,
  KEY `FK_HP_ID` (`hp_ID`),
  CONSTRAINT `FK_HP_ID` FOREIGN KEY (`hp_ID`) REFERENCES `proc_history_and_planning` (`hp_ID`),
  KEY `FK_HP_J_CMTF_ID` (`cmtf_ID`),
  CONSTRAINT `FK_HP_J_CMTF_ID` FOREIGN KEY (`cmtf_ID`) REFERENCES `contract_method_type_fundveh` (`cmtf_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;