package mil.dtic.cbes.p40.vo.auto;

import java.util.Date;
import java.util.List;

import mil.dtic.cbes.p40.vo.Base;
import mil.dtic.cbes.p40.vo.P40User;
import mil.dtic.cbes.p40.vo.SubmissionDate;

/**
 * _BudgetCycleConfig.java was generated by Cayenne.
 *
 * DO NOT EDIT THIS CLASS!
 *
 * _BudgetCycleConfig.java WILL be overwritten the next time
 * classes are generated.
 *
 * You WILL lose your changes if you manually edit.
 *
 * DO NOT EDIT THIS CLASS!
 *
 * If you need to make any customizations, use the subclass.
 */
public abstract class _BudgetCycleConfig extends Base
{
    private static final long serialVersionUID = 1L;

    // Attribute Keys
    public static final String AMENDED_PROPERTY = "amended";
    public static final String BUDGET_YEAR_PROPERTY = "budgetYear";
    public static final String CREATED_PROPERTY = "created";
    public static final String CYCLE_PROPERTY = "cycle";
    public static final String LABEL_PROPERTY = "label";

    // Relationship Keys
    public static final String CREATOR_RELATIONSHIP_PROPERTY = "creator";
    public static final String SUBMISSION_DATES_RELATIONSHIP_PROPERTY = "submissionDates";

    // Primary Keys
    public static final String ID_PK_COLUMN = "ID";

    // Attribute Setters/Getters
    public void setAmended(Integer amended)
    {
        writeProperty(AMENDED_PROPERTY, amended);
    }
    public Integer getAmended()
    {
        return (Integer)readProperty(AMENDED_PROPERTY);
    }

    public void setBudgetYear(Integer budgetYear)
    {
        writeProperty(BUDGET_YEAR_PROPERTY, budgetYear);
    }
    public Integer getBudgetYear()
    {
        return (Integer)readProperty(BUDGET_YEAR_PROPERTY);
    }

    public void setCreated(Date created)
    {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated()
    {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setCycle(String cycle)
    {
        writeProperty(CYCLE_PROPERTY, cycle);
    }
    public String getCycle()
    {
        return (String)readProperty(CYCLE_PROPERTY);
    }

    public void setLabel(String label)
    {
        writeProperty(LABEL_PROPERTY, label);
    }
    public String getLabel()
    {
        return (String)readProperty(LABEL_PROPERTY);
    }

    // Relationships
    public void setCreator(P40User creator)
    {
        setToOneTarget(CREATOR_RELATIONSHIP_PROPERTY, creator, true);
    }

    public P40User getCreator()
    {
        return (P40User)readProperty(CREATOR_RELATIONSHIP_PROPERTY);
    }


    public void addToSubmissionDates(SubmissionDate obj)
    {
        addToManyTarget(SUBMISSION_DATES_RELATIONSHIP_PROPERTY, obj, true);
    }
    public void removeFromSubmissionDates(SubmissionDate obj)
    {
        removeToManyTarget(SUBMISSION_DATES_RELATIONSHIP_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SubmissionDate> getSubmissionDates()
    {
        return (List<SubmissionDate>)readProperty(SUBMISSION_DATES_RELATIONSHIP_PROPERTY);
    }


    // Callbacks
}
