ALTER TABLE `PROJECT_COST_CATEGORY_ITEM` 
CHANGE COLUMN `PCCI_PERF_ACTIVITY` `PCCI_PERF_ACTIVITY` VARCHAR(255) NULL COMMENT '' ,
CHANGE COLUMN `PCCI_PERF_ACT_LOCATION` `PCCI_PERF_ACT_LOCATION` VARCHAR(255) NULL COMMENT '' ;