ALTER TABLE hp_to_cmtf
    CHANGE COLUMN `DATE_CREATED` `DATE_CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '' ,
    CHANGE COLUMN `DATE_MODIFIED` `DATE_MODIFIED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '' ;
