SET NAMES utf8;
SET UNIQUE_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET SQL_NOTES=0;
ALTER TABLE PGM_ELEMENT CHANGE `DATE_CREATED_R2` `DATE_CREATED_R2` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  ;
ALTER TABLE PGM_ELEMENT CHANGE `DATE_MODIFIED_R2` `DATE_MODIFIED_R2` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ;
