INSERT IGNORE INTO `PE_SUFFIX`(`PS_SERV_AGY_ID`, `PS_SUFFIX`, `PS_DATE_ACTIVE`)
VALUES (
  (SELECT `BUDGES_SERV_AGY_ID` FROM `SERVICE_AGENCY` WHERE `BUDGES_SERV_AGY_CODE` = 'DCAA'),
  'R', CURRENT_TIMESTAMP
);