CREATE TABLE `P1Data` (
  `p1data_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `account` varchar(50) NOT NULL,
  `accountTitle` varchar(100) NOT NULL,
  `organization` varchar(50) NOT NULL,
  `budgetActivity` varchar(50) NOT NULL,
  `budgetActivityTitle` varchar(100) NOT NULL,
  `lineNumber` varchar(50) NOT NULL,
  `budgetSubActivity` varchar(50) NOT NULL,
  `budgetSubActivityTitle` varchar(100) NOT NULL,
  `liNumber` varchar(50) NOT NULL,
  `liTitle` varchar(100) NOT NULL,
  `costType` varchar(50) NOT NULL,
  `costTypeTitle` varchar(100) NOT NULL,
  `addNonAdd` varchar(50) NOT NULL,
  `pyQuantity` decimal(12,3) NOT NULL,
  `pyAmount` decimal(12,3) NOT NULL,
  `cyQuantity` decimal(12,3) NOT NULL,
  `cyAmount` decimal(12,3) NOT NULL,
  `by1Quantity` decimal(12,3) NOT NULL,
  `by1Amount` decimal(12,3) NOT NULL,  
  `by2Quantity` decimal(12,3) NOT NULL,
  `by2Amount` decimal(12,3) NOT NULL, 
  `by3Quantity` decimal(12,3) NOT NULL,
  `by3Amount` decimal(12,3) NOT NULL,
  `by4Quantity` decimal(12,3) NOT NULL,
  `by4Amount` decimal(12,3) NOT NULL,
  `by5Quantity` decimal(12,3) NOT NULL,
  `by5Amount` decimal(12,3) NOT NULL,
  `classification` varchar(5) NOT NULL,
  `budgetYear` int(4) NOT NULL,
  `created_by_user` varchar(256) DEFAULT NULL,
  `date_created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by_user` varchar(256) DEFAULT NULL,
  `date_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`p1data_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
