SET @DHP_APPROP = (SELECT BUDGES_APPROP_ACCT_ID FROM SERVICE_AGENCY WHERE BUDGES_SERV_AGY_CODE = 'DHP');

INSERT into SERVICE_AGENCY (BUDGES_SERV_AGY_CODE, SERV_AGY_NAME, BUDGES_APPROP_ACCT_ID, sa_status_flag, sa_SMCA_tag, LOGO_FILE_NAME, NO_WARNING) 
values ('DHA', 'Defense Health Agency', @DHP_APPROP, 'A', 0, 'DW.png', 'N');