CREATE TABLE `R1Data` (
  `r1data_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `account` varchar(50) NOT NULL,
  `accountTitle` varchar(100) NOT NULL,
  `organization` varchar(50) NOT NULL,
  `budgetActivity` varchar(50) NOT NULL,
  `budgetActivityTitle` varchar(100) NOT NULL,
  `lineNumber` varchar(50) NOT NULL,
  `peNumber` varchar(50) NOT NULL,
  `peTitle` varchar(100) NOT NULL,
  `projectNumber` varchar(50) NOT NULL,
  `projectTitle` varchar(100) NOT NULL,
  `fundCategory` varchar(50) NOT NULL,
  `pyAmount` decimal(12,3) NOT NULL,
  `cyAmount` decimal(12,3) NOT NULL,
  `by1Amount` decimal(12,3) NOT NULL,  
  `by2Amount` decimal(12,3) NOT NULL, 
  `by3Amount` decimal(12,3) NOT NULL,
  `by4Amount` decimal(12,3) NOT NULL,
  `by5Amount` decimal(12,3) NOT NULL,
  `classification` varchar(5) NOT NULL,
  `budgetYear` int(4) NOT NULL,
  `created_by_user` varchar(256) DEFAULT NULL,
  `date_created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by_user` varchar(256) DEFAULT NULL,
  `date_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`r1data_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;