ALTER TABLE   `proc_ships_characteristics` 
  DROP COLUMN `sch_crew_size_footnote` , 
  DROP COLUMN `sch_crew_size` , 
  DROP COLUMN `sch_installed_power_footnote` , 
  DROP COLUMN `sch_installed_power` , 
  DROP COLUMN `sch_speed_footnote` , 
  DROP COLUMN `sch_speed` , 
  
  CHANGE COLUMN `sch_length`                `sch_length_value`                VARCHAR(255) NULL DEFAULT NULL  , 
  CHANGE COLUMN `sch_length_footnote`       `sch_length_value_footnote`       TEXT         NULL DEFAULT NULL  , 
  CHANGE COLUMN `sch_beam`                  `sch_beam_value`                  VARCHAR(255) NULL DEFAULT NULL  , 
  CHANGE COLUMN `sch_beam_footnote`         `sch_beam_value_footnote`         TEXT         NULL DEFAULT NULL  , 
  CHANGE COLUMN `sch_displacement`          `sch_displacement_value`          VARCHAR(255) NULL DEFAULT NULL  , 
  CHANGE COLUMN `sch_displacement_footnote` `sch_displacement_value_footnote` TEXT         NULL DEFAULT NULL  , 
  CHANGE COLUMN `sch_draft`                 `sch_draft_value`                 VARCHAR(255) NULL DEFAULT NULL  , 
  CHANGE COLUMN `sch_draft_footnote`        `sch_draft_value_footnote`        TEXT         NULL DEFAULT NULL  , 
  
  ADD COLUMN `sch_length_unit`                 VARCHAR(255) NULL  AFTER `sch_length_value_footnote` , 
  ADD COLUMN `sch_length_unit_footnote`        TEXT         NULL  AFTER `sch_length_unit` , 
  ADD COLUMN `sch_beam_unit`                   VARCHAR(255) NULL  AFTER `sch_beam_value_footnote` , 
  ADD COLUMN `sch_beam_unit_footnote`          TEXT         NULL  AFTER `sch_beam_unit` , 
  ADD COLUMN `sch_displacement_unit`           VARCHAR(255) NULL  AFTER `sch_displacement_value_footnote` , 
  ADD COLUMN `sch_displacement_unit_footnote`  TEXT         NULL  AFTER `sch_displacement_unit` , 
  ADD COLUMN `sch_draft_unit`                  VARCHAR(255) NULL  AFTER `sch_draft_value_footnote` , 
  ADD COLUMN `sch_draft_unit_footnote`         TEXT         NULL  AFTER `sch_draft_unit` ,
  ADD COLUMN `sch_value_header_label`          VARCHAR(255) NULL  AFTER `sch_draft_unit_footnote` ,
  ADD COLUMN `sch_value_header_label_footnote` TEXT         NULL  AFTER `sch_value_header_label` ,
  ADD COLUMN `sch_unit_header_label`           VARCHAR(255) NULL  AFTER `sch_value_header_label_footnote` ,
  ADD COLUMN `sch_unit_header_label_footnote`  TEXT         NULL  AFTER `sch_unit_header_label`;
