SET NAMES utf8;
SET TIME_ZONE='+00:00';
SET UNIQUE_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET SQL_NOTES=0;

CREATE ALGORITHM=UNDEFINED
VIEW `PE_LIST_PROJECT_TMP` AS
SELECT `PT`.`BUDGES_PROJ_ID` AS `BUDGES_PROJ_ID`,
	   `PE`.`BUDGES_PGM_ELEM_ID` AS `BUDGES_PGM_ELEM_ID`,
       `PT`.`MODIFIED_BY_USER_ID_R2A` AS `MODIFIED_BY_USER_ID_R2A`,
       `PT`.`DATE_MODIFIED_R2A` AS `DATE_MODIFIED_R2A`,
       `PT`.`DATE_CREATED_R3` AS `DATE_CREATED_R3`,
       `PT`.`DATE_CREATED_R4` AS `DATE_CREATED_R4`,
       `PT`.`DATE_CREATED_R4A` AS `DATE_CREATED_R4A`,
       `PT`.`DATE_CREATED_R5` AS `DATE_CREATED_R5`,
       `PT`.`EDIT_LOCK_ID_PJ` AS `EDIT_LOCK_ID_PJ`,
	   `UC`.`FULL_NAME` AS `FULL_NAME`,
	   `UC`.`FIRST_NAME` AS `FIRST_NAME`,
	   `UC`.`MIDDLE_INITIAL` AS `MIDDLE_INITIAL`,
	   `UC`.`LAST_NAME` AS `LAST_NAME`,
	   `UC`.`USER_LDAP_ID` AS `USER_LDAP_ID`
FROM ((((`PGM_ELEMENT` `PE` left join `USER` `UC` on((`UC`.`BUDGES_USER_ID` = `PE`.`CREATED_BY_USER_ID_R2`))) left join `PROJECT` `PT` on((`PT`.`BUDGES_PGM_ELEM_ID` = `PE`.`BUDGES_PGM_ELEM_ID`)))))
  group by `PE`.`BUDGES_PGM_ELEM_ID`;