ALTER TABLE `PROJECT`
  MODIFY COLUMN `PROJ_pys_delta` INT UNSIGNED AFTER `PROJ_TOTAL_COST`,
  MODIFY COLUMN `PROJ_TITLE` VARCHAR(255) NOT NULL AFTER `BUDGES_PROJ_NUM`,
  MODIFY COLUMN `proj_special_project` TINYINT(1) NOT NULL DEFAULT 0 AFTER `PROJ_TITLE`,
  MODIFY COLUMN `proj_MDAP` VARCHAR(4) DEFAULT NULL AFTER `PROJ_pys_delta`;
