ALTER TABLE `proc_ships_cost_cat` CHANGE COLUMN `scc_category` `scc_category` 
ENUM('PLAN_COSTS','BASIC_CONSTRUCTION_CONVERSION','CHANGE_ORDERS','ELECTRONICS','TECHNOLOGY_INSERTION','PROPULSION_EQUIPMENT','HME','ORDNANCE','ESCALATION','OTHER_COST','USER_DEFINED') DEFAULT NULL  ;
