INSERT INTO `RDTE_RULE_STATUS` (`RULE_NUMBER`, `RULE_STATUS`, `RULE_ACTIVE_DATE`, `RULE_INACTIVE_DATE`)
VALUES
('RDTE#R2a-590', 1, NULL, CURRENT_TIMESTAMP),
('RDTE#R2a-600', 1, NULL, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE `RULE_STATUS`=1, `RULE_ACTIVE_DATE`= NULL, `RULE_INACTIVE_DATE` = CURRENT_TIMESTAMP, `MODIFIED_BY_USER_ID` = NULL;