SET FOREIGN_KEY_CHECKS=0;
SET UNIQUE_CHECKS=0;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';

INSERT INTO `config`
(`cf_name`,`cf_value`,`cf_type`,`cf_desc`,`cf_env`,`cf_cycle`,`cf_year`,`cf_read_only`)
VALUES
('jbwiz.help','<ul><li>Hover over the Help link on each step of the wizard for detailed instructions.</li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.help','<ul><li>Hover over the Help link on each step of the wizard for detailed instructions.</li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.p40BasicInfoHelp','<ul><li>Select your "Service/Agency", check "Force Even Pages", and click "Continue" to open the "P-40 Exhibit Selection" page.</li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.p40BasicInfoHelp','<ul><li>Select your "Service/Agency", check "Force Even Pages", and click "Continue" to open the "P-40 Exhibit Selection" page.</li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.r2BasicInfoHelp','<ul><li>Select your "Service/Agency", check "Force Even Pages", and click "Continue" to open the "PE Selection" page.</li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.r2BasicInfoHelp','<ul><li>Select your "Service/Agency", check "Force Even Pages", and click "Continue" to open the "PE Selection" page.</li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.p40ExhibitSelectHelp','<ul><li>Select the "Select from P-40s That Exist on This System" radio button and then click "Select P-40s" button; which will open the "Select Exhibit P-40s" page.<ul><li>a. Select the appropriate P-40s from the "Available Exhibit P-40''s" list on the left and add these to the "Selected" list on the right by clicking on the "Add All" or "Add All Highlighted" button.<ul><li>i. Hint: You can narrow your selections by entering appropriate parameters in the "Filter" section at the top of the Available Exhibit P-40''s listing or adding additional Columns to the table and sorting by selected Column values (e.g., Agency, BA#, etc.).</li></ul></li><li>b. Once P-40 selections are complete click the "Return to JB Wizard With Selections" button, scroll to the bottom of the page, and click "Continue" to open the "Volumes" page.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.p40ExhibitSelectHelp','<ul><li>Select the "Select from P-40s That Exist on This System" radio button and then click "Select P-40s" button; which will open the "Select Exhibit P-40s" page.<ul><li>a. Select the appropriate P-40s from the "Available Exhibit P-40''s" list on the left and add these to the "Selected" list on the right by clicking on the "Add All" or "Add All Highlighted" button.<ul><li>i. Hint: You can narrow your selections by entering appropriate parameters in the "Filter" section at the top of the Available Exhibit P-40''s listing or adding additional Columns to the table and sorting by selected Column values (e.g., Agency, BA#, etc.).</li></ul></li><li>b. Once P-40 selections are complete click the "Return to JB Wizard With Selections" button, scroll to the bottom of the page, and click "Continue" to open the "Volumes" page.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.r2ExhibitSelectHelp','<ul><li>Select the "Select from Exhibit R-2s That Exist on This System" radio button and then click "Select R-2s" button; which will open the "Exhibit R-2 Selections for Document Build" page.<ul><li>a. Select the appropriate R-2s from the "Available Exhibit R-2''s" list on the left and add these to the "Exhibit R-2''s To Include In Justification Book/Other Documents" list on the right by clicking on the "Add Selected" button.</li><ul><li>i. Hint: You can narrow your selections by entering appropriate parameters in the "Narrow Displayed Exhibit R-2''s" section at the top of the page and clicking on the "Refresh" button.</li></ul><li>b. Once PE selections are complete click the "Return to JB Wizard" button, scroll to the bottom of the page and click "Continue" to open the "Volumes" page.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.r2ExhibitSelectHelp','<ul><li>Select the "Select from Exhibit R-2s That Exist on This System" radio button and then click "Select R-2s" button; which will open the "Exhibit R-2 Selections for Document Build" page.<ul><li>a. Select the appropriate R-2s from the "Available Exhibit R-2''s" list on the left and add these to the "Exhibit R-2''s To Include In Justification Book/Other Documents" list on the right by clicking on the "Add Selected" button.</li><ul><li>i. Hint: You can narrow your selections by entering appropriate parameters in the "Narrow Displayed Exhibit R-2''s" section at the top of the page and clicking on the "Refresh" button.</li></ul><li>b. Once PE selections are complete click the "Return to JB Wizard" button, scroll to the bottom of the page and click "Continue" to open the "Volumes" page.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.singleVolumesHelp','<ul><li>Check "Include TOV" and enter other Volume information, including the optional Volume Title, Volume Description and Volume Number if desired:<ul><li>a. There must be at least one volume.</li><li>b. The Volume Number must be unique.</li><li>c. If provided, the Volume Title will appear on the Volume''s cover page.</li><li>d. Click "Continue" to open the "Table of Contents" page.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.singleVolumesHelp','<ul><li>Check "Include TOV" and enter other Volume information, including the optional Volume Title, Volume Description and Volume Number if desired:<ul><li>a. There must be at least one volume.</li><li>b. The Volume Number must be unique.</li><li>c. If provided, the Volume Title will appear on the Volume''s cover page.</li><li>d. Click "Continue" to open the "Table of Contents" page.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.multiVolumesHelp','<ul><li>Create as many Volumes as desired by clicking on the "Add Volume" link at the bottom of the "Volume Description and Number" table.<ul><li>a. Check "Include TOV" and enter other Volume information for each of the Volumes.</li><li>b. The Volume Number must be unique.</li><li>c. If provided, the Volume Title will appear on the Volume''s cover page.</li><li>d. Click "Continue" to open the "Table of Contents" page.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.multiVolumesHelp','<ul><li>Create as many Volumes as desired by clicking on the "Add Volume" link at the bottom of the "Volume Description and Number" table.<ul><li>a. Check "Include TOV" and enter other Volume information for each of the Volumes.</li><li>b. The Volume Number must be unique.</li><li>c. If provided, the Volume Title will appear on the Volume''s cover page.</li><li>d. Click "Continue" to open the "Table of Contents" page.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.p40TableOfContentsHelp','<ul><li>Insure "Generate Volume Exhibit P-1" is deselected and select any additional Line Item Table of Contents Options. Click "Continue" to open the "P-40 Volume Breakdown" page.<ul><li>a. Note: When building a Justification Book via the wizard, do NOT select "Generate Volume Exhibit P-1". Instead, for the PB budget cycle, the "Comptroller P-1 Exhibit" must be a PDF from PRCP and included as an attachment to the Justification Book. Follow the wizard steps to upload it in "Step 6 Attachments" below.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.p40TableOfContentsHelp','<ul><li>Insure "Generate Volume Exhibit P-1" is deselected and select any additional Line Item Table of Contents Options. Click "Continue" to open the "P-40 Volume Breakdown" page.<ul><li>a. Note: When building a Justification Book via the wizard, do NOT select "Generate Volume Exhibit P-1". Instead, for the PB budget cycle, the "Comptroller P-1 Exhibit" must be a PDF from PRCP and included as an attachment to the Justification Book. Follow the wizard steps to upload it in "Step 6 Attachments" below.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.r2TableOfContentsHelp','<ul><li>Deselect "Generate Volume Exhibit R-1", and click "Continue" to open the "PE Volume Breakdown" page.<ul><li>a. Note: When building a Justification Book via the wizard, do NOT select "Generate Volume Exhibit R-1". Instead, for the PB budget cycle, the "Comptroller R-1 Exhibit" must be a PDF from PRCP and included as an attachment to the Justification Book. Follow the wizard steps to upload it in "Step 6 Attachments" below.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.r2TableOfContentsHelp','<ul><li>Deselect "Generate Volume Exhibit R-1", and click "Continue" to open the "PE Volume Breakdown" page.<ul><li>a. Note: When building a Justification Book via the wizard, do NOT select "Generate Volume Exhibit R-1". Instead, for the PB budget cycle, the "Comptroller R-1 Exhibit" must be a PDF from PRCP and included as an attachment to the Justification Book. Follow the wizard steps to upload it in "Step 6 Attachments" below.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.singleVolumeBreakdownHelp','<ul><li>Scroll to the bottom of the page and click "Continue" to open the "Attachments" page.</li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.singleVolumeBreakdownHelp','<ul><li>Scroll to the bottom of the page and click "Continue" to open the "Attachments" page.</li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.p40MultiVolumeBreakdownHelp','<ul><li>Choose which P-40s go in each volume:<ul><li>a. All the P-40s originally selected for inclusion in the JBook will default to the first Volume.</li><li>b. Select the P-40s to be moved to a different Volume by holding down the "Ctrl" key and clicking on them.</li><li>c. After all the desired P-40s are highlighted, click on the "Bring highlighted P-40s from other Volumes to this Volume" button under the Volume you wish to move them to.</li><li>d. Once the P-40s have been distributed to the desired Volumes, scroll to the bottom of the page and click "Continue" to open the "Attachments" page.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.p40MultiVolumeBreakdownHelp','<ul><li>Choose which P-40s go in each volume:<ul><li>a. All the P-40s originally selected for inclusion in the JBook will default to the first Volume.</li><li>b. Select the P-40s to be moved to a different Volume by holding down the "Ctrl" key and clicking on them.</li><li>c. After all the desired P-40s are highlighted, click on the "Bring highlighted P-40s from other Volumes to this Volume" button under the Volume you wish to move them to.</li><li>d. Once the P-40s have been distributed to the desired Volumes, scroll to the bottom of the page and click "Continue" to open the "Attachments" page.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.r2MultiVolumeBreakdownHelp','<ul><li>Choose which PEs go in each volume:<ul><li>a. All the PEs originally selected for inclusion in the JBook will default to the first Volume.</li><li>b. Select the PEs to be moved to a different Volume by holding down the "Ctrl" key and clicking on them.</li><li>c. After all the desired PEs are highlighted, click on the "Bring highlighted Program Elements from other Volumes to this Volume" button under the Volume you wish to move them to.</li><li>d. Once the PEs have been distributed to the desired Volumes, scroll to the bottom of the page and click "Continue" to open the "Attachments" page.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.r2MultiVolumeBreakdownHelp','<ul><li>Choose which PEs go in each volume:<ul><li>a. All the PEs originally selected for inclusion in the JBook will default to the first Volume.</li><li>b. Select the PEs to be moved to a different Volume by holding down the "Ctrl" key and clicking on them.</li><li>c. After all the desired PEs are highlighted, click on the "Bring highlighted Program Elements from other Volumes to this Volume" button under the Volume you wish to move them to.</li><li>d. Once the PEs have been distributed to the desired Volumes, scroll to the bottom of the page and click "Continue" to open the "Attachments" page.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.p40AttachmentsHelp','<ul><li>As a minimum, include a PDF version (must be a PDF) of the Comptroller''s P-1 from PRCP:<ul><li>a. To upload the "Comptroller Exhibit P-1 Document", select the checkbox in the "Volume" column to the left of the Comptroller Exhibit P-1 Document section, and browse to the PDF location. Add any other attachments as necessary and click on the "Upload Logo and Attachments" button at the bottom of the page.</li><li>b. Once Attachments have been uploaded, click "Continue" to open the "Summary and Build" page.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.p40AttachmentsHelp','<ul><li>As a minimum, include a PDF version (must be a PDF) of the Comptroller''s P-1 from PRCP:<ul><li>a. To upload the "Comptroller Exhibit P-1 Document", select the checkbox in the "Volume" column to the left of the Comptroller Exhibit P-1 Document section, and browse to the PDF location. Add any other attachments as necessary and click on the "Upload Logo and Attachments" button at the bottom of the page.</li><li>b. Once Attachments have been uploaded, click "Continue" to open the "Summary and Build" page.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.r2AttachmentsHelp','<ul><li>As a minimum, include a PDF version (must be a PDF) of the Comptroller''s R-1 from PRCP.<ul><li>a. To upload the "Comptroller Exhibit R-1 Document", select the checkbox in the "Volume 5" column to the left of the Comptroller Exhibit R-1 Document section, and browse to the PDF location. Add any other attachments as necessary and click on the "Upload Logo and Attachments" button at the bottom of the page.</li><li>b. Once Attachments have been uploaded, click Continue" to open the "Summary and Build" page.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.r2AttachmentsHelp','<ul><li>As a minimum, include a PDF version (must be a PDF) of the Comptroller''s R-1 from PRCP.<ul><li>a. To upload the "Comptroller Exhibit R-1 Document", select the checkbox in the "Volume 5" column to the left of the Comptroller Exhibit R-1 Document section, and browse to the PDF location. Add any other attachments as necessary and click on the "Upload Logo and Attachments" button at the bottom of the page.</li><li>b. Once Attachments have been uploaded, click Continue" to open the "Summary and Build" page.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.summaryAndBuildHelp','<ul></li>Verify selections and click the "Build Book" button at the bottom of the page to open the "Confirmation" page.</li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.summaryAndBuildHelp','<ul></li>Verify selections and click the "Build Book" button at the bottom of the page to open the "Confirmation" page.</li></ul>','STRING',NULL,'default','xxxxx',null,1),
('jbwiz.confirmationHelp','<ul><li>This page will display a link to the JBook build status. Selecting it will open the "Document Tracking" page.<ul><li>a. Once the "Status" for the Jbook on the "Document Tracking" page shows "Completed successfully" the Jbook build is complete.</li><li>b. Select the link for the Jbook under "Tracking Number" to download the completed book.</li></ul></li></ul>','STRING',NULL,'default','PB',2015,1),
('jbwiz.confirmationHelp','<ul><li>This page will display a link to the JBook build status. Selecting it will open the "Document Tracking" page.<ul><li>a. Once the "Status" for the Jbook on the "Document Tracking" page shows "Completed successfully" the Jbook build is complete.</li><li>b. Select the link for the Jbook under "Tracking Number" to download the completed book.</li></ul></li></ul>','STRING',NULL,'default','xxxxx',null,1);