SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `RDTE_RULE_STATUS` (
  `RULE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `RULE_NUMBER` varchar(16) NOT NULL,
  `RULE_STATUS` int(2) NOT NULL,
  `RULE_ACTIVE_DATE` datetime DEFAULT NULL,
  `RULE_INACTIVE_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY_USER_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY_USER` varchar(256) DEFAULT NULL,
  `DATE_CREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MODIFIED_BY_USER` varchar(256) DEFAULT NULL,
  `DATE_MODIFIED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`RULE_ID`),
  UNIQUE KEY `UN_RULE_NUMBER` (`RULE_NUMBER`) USING BTREE,
  KEY `FK_RS_MOD_USER_ID` (`MODIFIED_BY_USER_ID`),
  CONSTRAINT `FK_RS_MOD_USER_ID` FOREIGN KEY (`MODIFIED_BY_USER_ID`) REFERENCES `USER` (`BUDGES_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;