insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '1' ,'Rockets', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '2' ,'Cartridge', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '3' ,'Bombs', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '4' ,'Targets', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '5' ,'Other Items', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '6' ,'Fuzes', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '7' ,'Munitions Undistributed', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '11' ,'Rockets', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '12' ,'Cartridges', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '13' ,'Bombs', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '14' ,'Items Less Than $2,000,000', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '15' ,'Other Items', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '17' ,'Munitions Undistributed', 'A');

insert into proc_budget_sub_activity (ba_ID, bsa_num, bsa_title, bsa_status_flag) values ((SELECT ba_ID FROM proc_budget_activity ba, APPROP_ACCOUNT a WHERE ba.ba_num = 1 AND ba.ba_title = 'Ammunition' AND a.BUDGES_APPROP_ACCT_CODE = '3011F' AND a.BUDGES_APPROP_ACCT_NAME = 'Procurement of Ammunition, Air Force' AND a.BUDGES_APPROP_ACCT_ID = ba.aa_id), '18' ,'Fuzes', 'A');