CREATE TABLE `proc_ships_contracts` (
  `sco_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `sc_ID` int(10) unsigned NOT NULL,
  `cmtf_ID` int(10) unsigned,
  `sird_ID` int(10) unsigned,
  `sco_shipbuilder` varchar(255) DEFAULT NULL,
  `sco_shipbuilder_footnote` text,
  `sco_fy_authorized` int(10) unsigned DEFAULT NULL,
  `sco_fy_authorized_footnote` text,
  `sco_contract_award` date DEFAULT NULL,
  `sco_contract_award_footnote` text,
  `sco_option_award` date DEFAULT NULL,
  `sco_option_award_footnote` text,
  `sco_construction_start` date DEFAULT NULL,
  `sco_construction_start_footnote` text,
  `sco_delivery` date DEFAULT NULL,
  `sco_delivery_footnote` text,
  `sco_cofo` date DEFAULT NULL,
  `sco_cofo_footnote` text,
  `sco_owl` date DEFAULT NULL,
  `sco_owl_footnote` text,
  `sco_actual_award` date DEFAULT NULL,
  `sco_actual_award_footnote` text,
  `sco_base` date DEFAULT NULL,
  `sco_base_footnote` text,
  `sco_termination` date DEFAULT NULL,
  `sco_termination_footnote` text,
  `sco_requirement` decimal(13,3) DEFAULT NULL,
  `sco_requirement_footnote` text,
  `sco_labor_split` decimal(5,2) DEFAULT NULL,
  `sco_labor_split_footnote` text,
  `sco_material_split` decimal(5,2) DEFAULT NULL,
  `sco_material_split_footnote` text,
  `sco_allowable_overhead` decimal(5,2) DEFAULT NULL,
  `sco_allowable_overhead_footnote` text,
  `sco_is_significant` tinyint(1) DEFAULT NULL,
  `date_created` timestamp NULL DEFAULT NULL,
  `created_by_user` varchar(255) DEFAULT NULL,
  `modified_by_user` varchar(255) DEFAULT NULL,
  `date_modified` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`sco_ID`),
  KEY `FK_sco_sc_ID` (`sc_ID`),
  CONSTRAINT `FK_sco_sc_ID` FOREIGN KEY (`sc_ID`) REFERENCES `proc_ships_class` (`sc_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8



