ALTER TABLE `PGM_ELEMENT` 
ADD UNIQUE INDEX `UN_BUDGES_PE_NUM_BUDGET_CYCLE` USING BTREE (`BUDGES_PGM_ELEM_NUM` ASC, `PE_BUDGET_CYCLE` ASC, `PE_BUDGET_YEAR` ASC, `BUDGES_BUDGET_ACTIVITY_ID` ASC, `PE_TEST` ASC);
