INSERT IGNORE into PE_SUFFIX (PS_SERV_AGY_ID, PS_SUFFIX) VALUES
((SELECT BUDGES_SERV_AGY_ID FROM SERVICE_AGENCY WHERE BUDGES_SERV_AGY_CODE = 'DHA'),'DHA'),
((SELECT BUDGES_SERV_AGY_ID FROM SERVICE_AGENCY WHERE BUDGES_SERV_AGY_CODE = 'DHA'),'HP');